POST http://localhost:3030/favs/QRRnWMrXT9E7C

{
     "jwt":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pY28iLCJwYXNzd29yZCI6ImxhbWlkdXBhc3N3b3JkIiwiaWF0IjoxNjgwNTI5MDY5fQ.g-BgMJmNhZn9I8WYfceBrh2nNtGFDPTXKkUXMJdg5Kg"
}

###
POST http://localhost:3030/addFav
Content-Type: application/json

{
     "id": "MC6eSuC3yypCU" 
}