POST   http://localhost:3030/favs/J2gKmtefFY5nPiEmne
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmVmZDk1NzliMWVjYWU4OGQwYzBlYiIsInVzZXJuYW1lIjoiTWFydGluQ2Fyb2JlbmUiLCJpYXQiOjE2ODA4MDExODUsImV4cCI6MTY4MTQwNTk4NX0.b7-2v2MMXi-nQrifKf6TJjxtiA7SUw0ZBUCRCmbZhWQ

